springdoc:
  swagger-ui:
    url: /docs/openapi3.json
    path: /docs/swagger
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
spotify:
  client-id: local-id
  client-secret: local-secret
  redirectUri: http://localhost:8080
google:
  client-id: local-id
  client-secret: local-secret
  redirectUri: http://localhost:8080
restClient:
  logging: true
jwt:
  secret: "ToiguaOaVf3o3wD8XSnJV10MlWo0exackfAofpscMqs="
---

spring:
  config:
    import: classpath:secret/application-prod.yml
    activate:
      on-profile: prod